update-asdf-and-dockerfile/action.yml

Current creates all commits that the action produces as the person who created the action. This makes little sense as when the action runs, the original creator has little to do with all of the subsequent PR's the action creates and may create confusion.
Changed the author to `GitHub <noreply@github.com>` from default (action creator). See docs for info:
https://github.com/peter-evans/create-pull-request#action-inputs

Change the action auto commit author

---

.gitignore
update-asdf-and-dockerfile/action.yml

As suggested by @katalaakkonen it would be great that the npm version will be locked in `package.json` and that when asdf auto updater will recommend updates in `.tool-versions` it would also touch the engines section of `package.json`
This PR tries to do exactly that.
Also it ignore .DS_Store files in git

Update npm & node versions in package.json engines

---

update-asdf-and-dockerfile/action.yml

Earlier version also updated the package.json engines even when it's updating python version 😓
This should limit this action to only trigger when nodejs is getting a update.
Also `jq` is installed there already according to the logs so i removed this step from the installation:
```
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
...
Get:30 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [13.6 kB]
Fetched 5427 kB in 1s (4489 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
jq is already the newest version (1.6-2.1ubuntu3).
```

Only run the package.json engines updates for nodejs plugin and not python

---

update-asdf-and-dockerfile/action.yml

Use a the `'` and wildcard `*` in the add pathspec to match all pacakge.json files and not encounter  `pathspec 'xxx' did not match any files` kind of error

add wildcard for package.json to not raise error if not existing

---

update-asdf-and-dockerfile/action.yml
update-python/action.yml

* Improve the LTS version upgrades with NodeJS so we don't actually need to install it to get the latest version
* Only update package.json engines when versions update
* Remove LTS option from python since it's not available there
This makes the action a bit faster since it doesn't need to install node/npm if the version will not be changing.

Improvements to LTS version upgrades

---

update-asdf-and-dockerfile/action.yml

This fixes a typo I made earlier here and should fix the automatic updates.
I tried to check if I could prevent these errors in the future with validating with https://github.com/mpalmer/action-validator but it didn't spot this issue and only gave errors from the inputs of these files.
I guess it doesn't work properly with composite type actions 😞 
Tech-Support thread: https://swappie.slack.com/archives/C9ABB0CTF/p1686052859569789

Fix LTS version upgrade related comparison typo

---

update-asdf-and-dockerfile/action.yml

Git add in git checkout action fails if we don't have the files present at all, which causes issues as it seeks package.json which we dont have in python projects. This makes those files conditional on if we're upgrading node.

Attempt at adding package files only on node upgrades

---

update-asdf-and-dockerfile/action.yml

This should make it a bit faster and cheaper

Update npm & node versions in engines section of package.json without installing nodejs or npm packages

---

update-asdf-and-dockerfile/action.yml

Inspired by what Kata suggested earlier for the node `package.json` engine updates.
I noticed that in few projects we have done this manually but forgotten to do it sometimes. I will share links to those PRs in our internal slack if asked separately since this is public repository.
This should help us to keep the python version between asdf and poetry in sync.

Update new python version automatically into poetry config pyproject.toml file too

---

update-asdf-and-dockerfile/action.yml

I introduced a bug in #17.
The asdf plugin setup step already installed poetry + python and if they are installed already asdf it will return error code 2

Don't install asdf plugins and languages again since they were already installed

---

update-asdf-and-dockerfile/action.yml

Continuing the saga from #17 & #18.
asdf plugins were installed automatically but the python & poetry still need to be installed manually 🤕

fix pyproject toml upgrades

---

update-asdf-and-dockerfile/action.yml
update-nodejs/action.yml
update-python/action.yml

One last step in saga started in #17, #18, #19 is to actually commit the files that it creates as part of the PR 😅
I used the [format](https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-format) function provided by github to allow the extra parameter to be empty in future plugins.

Add poetry files to the created PRs created by python action and refactor extra files into input parameter

---

.github/pull_request_template.md

I don't think it's too dangerous but we probably don't want to link internal repositories into this repository.
Github doesn't really make it crystal clear which repos are private and which are public.

Add Pull Request template to warn that this is a publicly available repository

---

update-asdf-and-dockerfile/action.yml

@katalaakkonen & @viktor-ku noticed that the latest node updates had been broken for a moment with the message `Failed to fetch the new NPM version`
This will make it a bit slower but hopefully more robust 🤞

Don't try to fetch NPM version with curl but actually install the latest nodejs with bundled npm version

---

update-asdf-and-dockerfile/action.yml
update-nodejs/action.yml
update-poetry/action.yml
update-python/action.yml

Here are couple of screenshots how PRs created by dependabot look like. I would want to reuse the same labels for the python/node/poetry updates as well since these belong in the same category (in my mind at least)

Mimick same labels as what Dependabot is already using in the same repositories

---

update-asdf-and-dockerfile/action.yml

The action tries to currently update the FROM clause even for poetry which is not desired since we don't inherit Poetry from other Docker image.

Skip updating the Dockerfile for Poetry

---

update-asdf-and-dockerfile/action.yml

The current order of using poetry and installing poetry was wrong and the poetry needs to be installed as the first step before updating the poetry version to pyproject.toml

Install poetry with asdf before using it

---

update-asdf-and-dockerfile/action.yml
update-nodejs/action.yml
update-poetry/action.yml
update-python/action.yml

This PR address two issues:
1.  When we try to update `poetry` (or any other plugin with latest version) we do not fetch the latest version eg:
This is due, according to the debug file, a comparaison being made here:
In our code we compare to `latest` and it is true but then there is an extra check that look if we specified `major` (not sure where this check comes from, certainly from an extra check that llok if we correctly specified either major, minor or patch but we have the same for "minor" and "patch" [eg](https://github.com/swappiehq/laakso/actions/runs/5935374728/job/16100597863#step:2:692)). Now we will always use `major`  
Full debug logs [here](https://github.com/swappiehq/laakso/actions/runs/5935374728/job/16100597863#step:2)
**Edit 1**: the problem might come from re-running …

Use correct SEMVER convention for major update 

---

update-asdf-and-dockerfile/action.yml

Address this [issue](https://github.com/swappiehq/laakso/pull/4729/files#r1315507995) to implement a fixed version inisde the .toml file for python update.

Implement fixed python version in .toml

---

update-asdf-and-dockerfile/action.yml

Noticed that the python upgrade action was failing to update the image version in dockerfile, this should fix it.

Fix python upgrade action to update image version in Dockerfile

---

update-asdf-and-dockerfile/action.yml

The `update-asdf-and-dockerfile` action is failing currently - https://github.com/swappiehq/hemuli/actions/runs/10088730501/job/27894955257

Bump used checkout action to v4, because v3 uses deprecated nodejs

---

update-asdf-and-dockerfile/action.yml
update-python/action.yml

Should fix random 
> Cannot read properties of undefined (reading 'number')
errors in update asdf actions, tested with internal service to work
Source for the idea:
https://github.com/peter-evans/create-pull-request/issues/2790
- [] After merging this I have tested this by manually triggering the action in one of the internal projects

Fix asdf update action failing
